#!/usr/bin/env python3
"""ZTAM tenant manager.

Tenant config is the source of truth for per-tenant routing metadata and policy
defaults. This tool validates tenant definitions and generates the OPA data file
used by policies/authz.rego.
"""

from __future__ import annotations

import argparse
import json
import re
import ssl
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import urlparse
from urllib import error, request


ROUTES_BEGIN_MARKER = "# __ZTAM_TENANT_ROUTES_BEGIN__ (generated by tenant_manager.py)"
ROUTES_END_MARKER = "# __ZTAM_TENANT_ROUTES_END__ (generated by tenant_manager.py)"
CLUSTERS_BEGIN_MARKER = "# __ZTAM_TENANT_CLUSTERS_BEGIN__ (generated by tenant_manager.py)"
CLUSTERS_END_MARKER = "# __ZTAM_TENANT_CLUSTERS_END__ (generated by tenant_manager.py)"

LOGIN_PATH_HINTS = ("/login", "/signin", "/sign-in", "/auth", "/account/login")
DEFAULT_ASSESS_PATHS = ["/", "/login", "/admin", "/dashboard", "/app"]
ROLE_WHITELIST = {"admin", "editor", "user", "viewer"}
TENANT_NAME_RE = re.compile(r"^[a-z][a-z0-9_-]{1,63}$")
HOSTNAME_RE = re.compile(r"^(?=.{1,253}$)([a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)(\.[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)*$")
ADAPTER_MODE_WHITELIST = {"headers", "translated_token"}
DB_TYPE_WHITELIST = {"mysql", "postgresql"}
HASH_ALGORITHM_WHITELIST = {"bcrypt"}
IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]{0,127}$")

SECURITY_HEADERS_LINES = [
    "                      response_headers_to_add:",
    "                        - header:",
    "                            key: Strict-Transport-Security",
    "                            value: \"max-age=63072000; includeSubDomains; preload\"",
    "                        - header:",
    "                            key: X-Content-Type-Options",
    "                            value: \"nosniff\"",
    "                        - header:",
    "                            key: X-Frame-Options",
    "                            value: \"SAMEORIGIN\"",
    "                        - header:",
    "                            key: Referrer-Policy",
    "                            value: \"strict-origin-when-cross-origin\"",
    "                        - header:",
    "                            key: Content-Security-Policy",
    "                            value: \"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'\"",
    "                        - header:",
    "                            key: Permissions-Policy",
    "                            value: \"geolocation=(), microphone=(), camera=(), payment=()\"",
    "                        - header:",
    "                            key: Cache-Control",
    "                            value: \"no-store\"",
]


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def parse_roles(value: Any) -> list[str]:
    if isinstance(value, list):
        roles = [str(item).strip() for item in value if str(item).strip()]
    elif isinstance(value, str):
        roles = [item.strip() for item in value.split(",") if item.strip()]
    else:
        raise ValueError("roles must be a JSON array or a comma-separated string")

    deduped: list[str] = []
    for role in roles:
        canonical = role.lower()
        if canonical in ROLE_WHITELIST and canonical not in deduped:
            deduped.append(canonical)
        elif canonical not in ROLE_WHITELIST:
            raise ValueError(f"unsupported role '{role}'. Allowed roles: admin, editor, user, viewer")
    if not deduped:
        raise ValueError("at least one role is required")
    return deduped


def default_permissions(role: str) -> dict[str, Any] | None:
    role_lower = role.lower()
    if role_lower == "admin":
        return None
    if role_lower == "editor":
        return {
            "allowed_paths": ["/api/"],
            "allowed_exact_paths": ["/", "/dashboard.html", "/favicon.ico"],
            "denied_paths": ["/admin/", "/admin"],
            "allowed_methods": ["GET", "POST", "PUT", "PATCH", "DELETE"],
        }
    if role_lower == "viewer":
        return {
            "allowed_paths": ["/api/"],
            "allowed_exact_paths": ["/", "/dashboard.html", "/favicon.ico"],
            "denied_paths": ["/admin/", "/admin"],
            "allowed_methods": ["GET"],
        }
    return {
        "allowed_paths": ["/api/"],
        "allowed_exact_paths": ["/", "/dashboard.html", "/favicon.ico"],
        "denied_paths": ["/admin/", "/admin"],
        "allowed_methods": ["GET", "POST", "DELETE"],
    }


def _validate_string_list(value: Any, field_name: str) -> list[str]:
    if not isinstance(value, list) or not all(isinstance(item, str) and item for item in value):
        raise ValueError(f"permissions.{field_name} must be a non-empty list of strings")
    return value


def _normalize_simple_string(value: Any, field_name: str, *, required: bool = False) -> str:
    text = str(value or "").strip()
    if required and not text:
        raise ValueError(f"{field_name} is required")
    return text


def _normalize_url_list(value: Any, field_name: str) -> list[str]:
    if value in (None, ""):
        return []
    if not isinstance(value, list):
        raise ValueError(f"{field_name} must be a list of URL strings")
    urls: list[str] = []
    for item in value:
        if not isinstance(item, str):
            raise ValueError(f"{field_name} entries must be strings")
        candidate = item.strip()
        if not candidate:
            continue
        parsed = urlparse(candidate)
        if parsed.scheme != "https":
            raise ValueError(f"{field_name} entries must start with https://")
        if not parsed.hostname:
            raise ValueError(f"{field_name} entries must include a host")
        if ".." in parsed.path or ".." in parsed.netloc:
            raise ValueError(f"{field_name} entries must not contain traversal sequences")
        urls.append(candidate)
    return list(dict.fromkeys(urls))


def _default_redirect_uris(hostname: str) -> list[str]:
    return [f"https://{hostname}/*"]


def _default_web_origins(hostname: str) -> list[str]:
    return [f"https://{hostname}"]


def normalize_db_credentials(raw_db: Any) -> dict[str, str]:
    if raw_db in (None, "", {}):
        return {}
    if not isinstance(raw_db, dict):
        raise ValueError("db_credentials must be an object")

    db_type = _normalize_simple_string(raw_db.get("db_type", "mysql"), "db_credentials.db_type", required=True).lower()
    if db_type not in DB_TYPE_WHITELIST:
        raise ValueError("db_credentials.db_type must be one of: mysql, postgresql")

    db_host = _normalize_simple_string(raw_db.get("db_host", ""), "db_credentials.db_host", required=True)
    if "/" in db_host or ".." in db_host:
        raise ValueError("db_credentials.db_host must not contain path or traversal sequences")

    db_port_raw = _normalize_simple_string(raw_db.get("db_port", "3306" if db_type == "mysql" else "5432"), "db_credentials.db_port", required=True)
    if not db_port_raw.isdigit():
        raise ValueError("db_credentials.db_port must be numeric")
    db_port = str(int(db_port_raw))
    if not (1 <= int(db_port) <= 65535):
        raise ValueError("db_credentials.db_port must be between 1 and 65535")

    db_name = _normalize_simple_string(raw_db.get("db_name", ""), "db_credentials.db_name", required=True)
    db_user = _normalize_simple_string(raw_db.get("db_user", ""), "db_credentials.db_user", required=True)
    db_password = _normalize_simple_string(raw_db.get("db_password", ""), "db_credentials.db_password", required=True)
    table_name = _normalize_simple_string(raw_db.get("table_name", "users"), "db_credentials.table_name", required=True)
    username_col = _normalize_simple_string(raw_db.get("username_col", "username"), "db_credentials.username_col", required=True)
    password_col = _normalize_simple_string(raw_db.get("password_col", "password_hash"), "db_credentials.password_col", required=True)
    role_col = _normalize_simple_string(raw_db.get("role_col", "role"), "db_credentials.role_col", required=True)
    hash_algorithm = _normalize_simple_string(raw_db.get("hash_algorithm", "bcrypt"), "db_credentials.hash_algorithm", required=True).lower()

    if hash_algorithm not in HASH_ALGORITHM_WHITELIST:
        raise ValueError("db_credentials.hash_algorithm must be 'bcrypt'")

    for field_name, candidate in (
        ("db_credentials.db_name", db_name),
        ("db_credentials.db_user", db_user),
        ("db_credentials.table_name", table_name),
        ("db_credentials.username_col", username_col),
        ("db_credentials.password_col", password_col),
        ("db_credentials.role_col", role_col),
    ):
        if not IDENTIFIER_RE.match(candidate):
            raise ValueError(f"{field_name} contains unsupported characters")

    return {
        "db_type": db_type,
        "db_host": db_host,
        "db_port": db_port,
        "db_name": db_name,
        "db_user": db_user,
        "db_password": db_password,
        "table_name": table_name,
        "username_col": username_col,
        "password_col": password_col,
        "role_col": role_col,
        "hash_algorithm": hash_algorithm,
    }


def normalize_permissions(raw_permissions: Any, roles: list[str]) -> dict[str, dict[str, list[str]]]:
    if raw_permissions is None:
        permissions: dict[str, dict[str, list[str]]] = {}
        for role in roles:
            default_perm = default_permissions(role)
            if default_perm is not None:
                permissions[role] = default_perm
        return permissions

    if not isinstance(raw_permissions, dict):
        raise ValueError("permissions must be an object keyed by role name")

    normalized: dict[str, dict[str, list[str]]] = {}
    for role, perms in raw_permissions.items():
        if not isinstance(role, str) or not role:
            raise ValueError("permission role names must be non-empty strings")
        if not isinstance(perms, dict):
            raise ValueError(f"permissions.{role} must be an object")
        normalized[role] = {
            "allowed_paths": _validate_string_list(perms.get("allowed_paths"), f"{role}.allowed_paths"),
            "allowed_exact_paths": perms.get("allowed_exact_paths", []),
            "denied_paths": perms.get("denied_paths", []),
            "denied_exact_paths": perms.get("denied_exact_paths", []),
            "allowed_methods": _validate_string_list(perms.get("allowed_methods"), f"{role}.allowed_methods"),
        }
        if not isinstance(normalized[role]["denied_paths"], list) or not all(
            isinstance(item, str) for item in normalized[role]["denied_paths"]
        ):
            raise ValueError(f"permissions.{role}.denied_paths must be a list of strings")
        if not isinstance(normalized[role]["allowed_exact_paths"], list) or not all(
            isinstance(item, str) for item in normalized[role]["allowed_exact_paths"]
        ):
            raise ValueError(f"permissions.{role}.allowed_exact_paths must be a list of strings")
        if not isinstance(normalized[role]["denied_exact_paths"], list) or not all(
            isinstance(item, str) for item in normalized[role]["denied_exact_paths"]
        ):
            raise ValueError(f"permissions.{role}.denied_exact_paths must be a list of strings")
    return normalized


def derive_backend_parts(backend_url: str) -> tuple[str, int, bool]:
    parsed = urlparse(backend_url)
    if parsed.scheme not in {"http", "https"}:
        raise ValueError("backend_url must start with http:// or https://")
    if not parsed.hostname:
        raise ValueError("backend_url must include a host")
    if parsed.username or parsed.password:
        raise ValueError("backend_url must not include credentials")
    if parsed.path and parsed.path not in {"", "/"}:
        raise ValueError("backend_url must not include a path segment")
    if ".." in parsed.netloc or ".." in parsed.path:
        raise ValueError("backend_url contains invalid traversal sequence")
    port = parsed.port if parsed.port else (443 if parsed.scheme == "https" else 80)
    return parsed.hostname, port, parsed.scheme == "https"


def normalize_tenant_config(raw_config: dict[str, Any], source: Path) -> dict[str, Any]:
    name = str(raw_config.get("name", "")).strip()
    if not name:
        raise ValueError("name is required")
    if not TENANT_NAME_RE.match(name):
        raise ValueError("name must match ^[a-z][a-z0-9_-]{1,63}$")

    backend_url = str(raw_config.get("backend_url", "")).strip()
    hostname = str(raw_config.get("hostname", "")).strip()
    if not backend_url:
        raise ValueError("backend_url is required")
    if not hostname:
        raise ValueError("hostname is required")
    if "/" in hostname or ".." in hostname:
        raise ValueError("hostname must not contain path or traversal sequences")
    if not HOSTNAME_RE.match(hostname.lower()):
        raise ValueError("hostname must be a valid DNS hostname")

    backend_host, backend_port, backend_tls = derive_backend_parts(backend_url)
    roles = parse_roles(raw_config.get("roles", []))
    permissions = normalize_permissions(raw_config.get("permissions"), roles)
    adapter_mode = str(raw_config.get("adapter_mode", "headers")).strip() or "headers"
    if adapter_mode not in ADAPTER_MODE_WHITELIST:
        raise ValueError("adapter_mode must be one of: headers, translated_token")
    login_mode = str(raw_config.get("login_mode", "form")).strip() or "form"
    if login_mode not in {"form", "keycloak"}:
        raise ValueError("login_mode must be one of: form, keycloak")

    redirect_uris = _normalize_url_list(raw_config.get("redirect_uris"), "redirect_uris")
    web_origins = _normalize_url_list(raw_config.get("web_origins"), "web_origins")
    if not redirect_uris:
        redirect_uris = _default_redirect_uris(hostname)
    if not web_origins:
        web_origins = _default_web_origins(hostname)

    db_credentials = normalize_db_credentials(raw_config.get("db_credentials"))

    return {
        "name": name,
        "display_name": str(raw_config.get("display_name", name)).strip() or name,
        "backend_url": backend_url,
        "backend_host": backend_host,
        "backend_port": backend_port,
        "backend_tls": backend_tls,
        "hostname": hostname,
        "keycloak_client_id": str(raw_config.get("keycloak_client_id", name)).strip() or name,
        "keycloak_realm": str(raw_config.get("keycloak_realm", "test-tenant")).strip() or "test-tenant",
        "keycloak_client_secret": str(raw_config.get("keycloak_client_secret", "")).strip(),
        "roles": roles,
        "login_mode": login_mode,
        "adapter_mode": adapter_mode,
        "downstream_jwt_secret": str(raw_config.get("downstream_jwt_secret", "")).strip(),
        "redirect_uris": redirect_uris,
        "web_origins": web_origins,
        "no_spi": bool(raw_config.get("no_spi", False)),
        "db_credentials": db_credentials,
        "permissions": permissions,
        "created_at": str(raw_config.get("created_at", utc_now())).strip() or utc_now(),
        "notes": str(raw_config.get("notes", "")).strip(),
        "source_file": str(source),
    }


def iter_tenant_files(tenants_dir: Path) -> list[Path]:
    files: list[Path] = []
    for path in sorted(tenants_dir.glob("*/config.json")):
        if path.parent.name == "_template":
            continue
        files.append(path)
    return files


def load_tenants(tenants_dir: Path) -> list[dict[str, Any]]:
    tenants: list[dict[str, Any]] = []
    seen_names: set[str] = set()
    seen_hosts: set[str] = set()
    for config_file in iter_tenant_files(tenants_dir):
        with config_file.open("r", encoding="utf-8") as handle:
            raw = json.load(handle)
        tenant = normalize_tenant_config(raw, config_file)
        if tenant["name"] in seen_names:
            raise ValueError(f"duplicate tenant name: {tenant['name']}")
        if tenant["hostname"] in seen_hosts:
            raise ValueError(f"duplicate hostname: {tenant['hostname']}")
        seen_names.add(tenant["name"])
        seen_hosts.add(tenant["hostname"])
        tenants.append(tenant)
    return tenants


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2)
        handle.write("\n")


def save_tenant_config(tenants_dir: Path, raw_config: dict[str, Any]) -> Path:
    tenant_dir = tenants_dir / str(raw_config["name"])
    config_path = tenant_dir / "config.json"
    normalized = normalize_tenant_config(raw_config, config_path)
    normalized.pop("source_file", None)
    write_json(config_path, normalized)
    return config_path


def _build_opener(insecure: bool, *, follow_redirects: bool) -> request.OpenerDirector:
    handlers: list[Any] = []
    if insecure:
        context = ssl.create_default_context()
        context.check_hostname = False
        context.verify_mode = ssl.CERT_NONE
        handlers.append(request.HTTPSHandler(context=context))
    if not follow_redirects:
        class NoRedirectHandler(request.HTTPRedirectHandler):
            def redirect_request(self, req, fp, code, msg, headers, newurl):
                return None

        handlers.append(NoRedirectHandler())
    return request.build_opener(*handlers)


def fetch_url(
    url: str,
    *,
    insecure: bool,
    timeout: int,
    headers: dict[str, str] | None = None,
    follow_redirects: bool = False,
) -> dict[str, Any]:
    opener = _build_opener(insecure, follow_redirects=follow_redirects)
    req = request.Request(url, method="GET")
    for key, value in (headers or {}).items():
        req.add_header(key, value)
    try:
        with opener.open(req, timeout=timeout) as response:
            body = response.read().decode("utf-8", errors="replace")
            return {
                "status": response.getcode(),
                "headers": {k.lower(): v for k, v in response.headers.items()},
                "body": body,
                "error": "",
            }
    except error.HTTPError as exc:
        return {
            "status": exc.code,
            "headers": {k.lower(): v for k, v in exc.headers.items()},
            "body": exc.read().decode("utf-8", errors="replace"),
            "error": "",
        }
    except Exception as exc:  # pragma: no cover - defensive probe wrapper
        return {
            "status": 0,
            "headers": {},
            "body": "",
            "error": str(exc),
        }


def assess_backend(
    backend_url: str,
    *,
    candidate_paths: list[str],
    insecure: bool,
    timeout: int,
) -> dict[str, Any]:
    findings: list[dict[str, Any]] = []
    login_hints: list[str] = []
    risk_notes: list[str] = []
    backend = backend_url.rstrip("/")
    parsed_backend = urlparse(backend_url)

    for path in candidate_paths:
        full_path = path if path.startswith("/") else f"/{path}"
        probe = fetch_url(
            f"{backend}{full_path}",
            insecure=insecure,
            timeout=timeout,
            headers={"Accept": "text/html,application/json;q=0.9,*/*;q=0.8"},
        )
        location = probe["headers"].get("location", "")
        set_cookie = probe["headers"].get("set-cookie", "")
        body = probe["body"]
        has_password_field = bool(re.search(r'type=["\']password["\']|name=["\']password["\']|current-password', body, re.I))
        mentions_login = bool(re.search(r'login|sign in|signin|authenticate', body, re.I))
        redirects_to_login = any(hint in location.lower() for hint in LOGIN_PATH_HINTS)
        findings.append(
            {
                "path": full_path,
                "status": probe["status"],
                "location": location,
                "set_cookie": bool(set_cookie),
                "password_field": has_password_field,
                "mentions_login": mentions_login,
                "error": probe["error"],
            }
        )

        if redirects_to_login:
            login_hints.append(f"{full_path} redirects to {location}")
            if full_path not in {"/", "/login"}:
                risk_notes.append(f"{full_path} still depends on the application's own login redirect")
        if has_password_field:
            login_hints.append(f"{full_path} contains a password field")
            if full_path in {"/", "/login"}:
                risk_notes.append(f"{full_path} exposes an application-managed login form")
        if mentions_login and full_path == "/":
            login_hints.append("root page looks like an application login experience")
        if set_cookie:
            risk_notes.append(f"{full_path} sets an application cookie")
        if location.startswith("http"):
            parsed_location = urlparse(location)
            if parsed_location.hostname and parsed_location.hostname != parsed_backend.hostname:
                risk_notes.append(f"{full_path} redirects to a different host: {parsed_location.hostname}")
        if probe["error"]:
            risk_notes.append(f"{full_path} probe failed: {probe['error']}")

    deduped_login_hints = list(dict.fromkeys(login_hints))
    deduped_risks = list(dict.fromkeys(risk_notes))
    recommended_login_mode = "form" if deduped_login_hints else "keycloak"
    integration_verdict = "good-fit"
    if any(item["status"] == 0 for item in findings):
        integration_verdict = "blocked"
    elif deduped_risks:
        integration_verdict = "needs-review"

    summary = []
    if deduped_login_hints:
        summary.append("Existing app login/session behavior detected")
    else:
        summary.append("No obvious built-in login flow detected from the probe")
    if deduped_risks:
        summary.append("Integration review needed for redirects/cookies or backend reachability")
    else:
        summary.append("No immediate reverse-proxy red flags detected")

    return {
        "backend_url": backend_url,
        "recommended_login_mode": recommended_login_mode,
        "integration_verdict": integration_verdict,
        "login_hints": deduped_login_hints,
        "risk_notes": deduped_risks,
        "summary": summary,
        "findings": findings,
    }


def render_tenant_vhost(tenant: dict[str, Any]) -> str:
    name = tenant["name"]
    hostname = tenant["hostname"]
    backend_host = tenant["backend_host"]
    login_mode = tenant["login_mode"]
    lines = [
        f"                    # ── Tenant: {name} ({login_mode} mode) ────────────────────",
        f"                    - name: {name}_vhost",
        f"                      domains: [\"{hostname}\"]",
        *SECURITY_HEADERS_LINES,
        "                      routes:",
        "                        - match:",
        "                            prefix: \"/ztam/\"",
        "                          route:",
        "                            cluster: auth_middleware_cluster",
        "                            timeout: 10s",
        "                          request_headers_to_add:",
        "                            - append_action: OVERWRITE_IF_EXISTS_OR_ADD",
        "                              header:",
        "                                key: x-ztam-internal-auth",
        "                                value: \"%ENVIRONMENT(ENVOY_AUTH_SHARED_SECRET)%\"",
        "                          typed_per_filter_config:",
        "                            envoy.filters.http.ext_authz:",
        "                              \"@type\": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute",
        "                              disabled: true",
        "                        - match:",
        "                            path: \"/api/auth/login\"",
        "                          route:",
        "                            cluster: auth_middleware_cluster",
        "                            prefix_rewrite: \"/login-proxy\"",
        "                            timeout: 10s",
        "                          request_headers_to_add:",
        "                            - append_action: OVERWRITE_IF_EXISTS_OR_ADD",
        "                              header:",
        "                                key: x-ztam-internal-auth",
        "                                value: \"%ENVIRONMENT(ENVOY_AUTH_SHARED_SECRET)%\"",
        "                          typed_per_filter_config:",
        "                            envoy.filters.http.ext_authz:",
        "                              \"@type\": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute",
        "                              disabled: true",
        "                        - match:",
        "                            path: \"/api/auth/logout\"",
        "                          route:",
        "                            cluster: auth_middleware_cluster",
        "                            prefix_rewrite: \"/logout\"",
        "                            timeout: 10s",
        "                          request_headers_to_add:",
        "                            - append_action: OVERWRITE_IF_EXISTS_OR_ADD",
        "                              header:",
        "                                key: x-ztam-internal-auth",
        "                                value: \"%ENVIRONMENT(ENVOY_AUTH_SHARED_SECRET)%\"",
        "                          typed_per_filter_config:",
        "                            envoy.filters.http.ext_authz:",
        "                              \"@type\": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute",
        "                              disabled: true",
        "                        - match:",
        "                            prefix: \"/static/\"",
        "                          route:",
        f"                            cluster: {name}_cluster",
        f"                            host_rewrite_literal: \"{backend_host}\"",
        "                            timeout: 10s",
        "                          typed_per_filter_config:",
        "                            envoy.filters.http.ext_authz:",
        "                              \"@type\": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute",
        "                              disabled: true",
        "                        - match:",
        "                            prefix: \"/\"",
        "                          route:",
        f"                            cluster: {name}_cluster",
        f"                            host_rewrite_literal: \"{backend_host}\"",
        "                            timeout: 30s",
    ]
    return "\n".join(lines)


def render_tenant_cluster(tenant: dict[str, Any]) -> str:
    name = tenant["name"]
    backend_host = tenant["backend_host"]
    backend_port = tenant["backend_port"]
    lines = [
        f"    # ── Tenant: {name} ─────────────────────────────────────────────────────",
        f"    - name: {name}_cluster",
        "      connect_timeout: 10s",
        "      type: LOGICAL_DNS",
        "      dns_lookup_family: V4_ONLY",
    ]
    if tenant["backend_tls"]:
        lines.extend([
            "      transport_socket:",
            "        name: envoy.transport_sockets.tls",
            "        typed_config:",
            "          \"@type\": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext",
            f"          sni: {backend_host}",
        ])
    lines.extend([
        "      load_assignment:",
        f"        cluster_name: {name}_cluster",
        "        endpoints:",
        "          - lb_endpoints:",
        "              - endpoint:",
        "                  address:",
        "                    socket_address:",
        f"                      address: {backend_host}",
        f"                      port_value: {backend_port}",
    ])
    return "\n".join(lines)


def _replace_generated_block(content: str, begin_marker: str, end_marker: str, generated: str) -> str:
    if begin_marker not in content or end_marker not in content:
        raise ValueError(f"missing generated block markers: {begin_marker} / {end_marker}")
    start = content.index(begin_marker) + len(begin_marker)
    end = content.index(end_marker)
    block = "\n"
    if generated.strip():
        block += generated.rstrip() + "\n"
    return content[:start] + block + content[end:]


def cmd_list(args: argparse.Namespace) -> int:
    tenants = load_tenants(Path(args.tenants_dir))
    if not tenants:
        print("No tenants found")
        return 0
    for tenant in tenants:
        print(
            f"{tenant['name']}\t{tenant['hostname']}\t{tenant['backend_url']}\t"
            f"login={tenant['login_mode']}\troles={','.join(tenant['roles'])}"
        )
    return 0


def cmd_validate(args: argparse.Namespace) -> int:
    tenants = load_tenants(Path(args.tenants_dir))
    print(f"Validated {len(tenants)} tenant config(s)")
    for tenant in tenants:
        print(f"  - {tenant['name']} ({tenant['hostname']})")
    return 0


def cmd_sync_policies(args: argparse.Namespace) -> int:
    tenants = load_tenants(Path(args.tenants_dir))
    policy_doc = {
        tenant["name"]: {
            "roles": tenant["permissions"],
        }
        for tenant in tenants
    }
    write_json(Path(args.output), policy_doc)
    print(f"Wrote {len(tenants)} tenant policy entr{'y' if len(tenants) == 1 else 'ies'} to {args.output}")
    return 0


def cmd_sync_auth(args: argparse.Namespace) -> int:
    tenants = load_tenants(Path(args.tenants_dir))
    payload = {
        "version": "v1",
        "generated_at": utc_now(),
        "tenants": [
            {
                "tenant_id": tenant["name"],
                "display_name": tenant["display_name"],
                "primary_hostname": tenant["hostname"],
                "integration_mode": "managed_oidc" if tenant["login_mode"] == "keycloak" else "form_bridge",
                "identity_mode": "federated_db" if tenant["db_credentials"] and not tenant["no_spi"] else "managed",
                "adapter_mode": tenant["adapter_mode"],
                "keycloak_realm": tenant["keycloak_realm"],
                "keycloak_client_id": tenant["keycloak_client_id"],
                "status": "published",
            }
            for tenant in tenants
        ],
    }
    write_json(Path(args.output), payload)
    print(f"Wrote {len(tenants)} auth metadata entr{'y' if len(tenants) == 1 else 'ies'} to {args.output}")
    return 0


def cmd_sync_envoy(args: argparse.Namespace) -> int:
    tenants = load_tenants(Path(args.tenants_dir))
    envoy_path = Path(args.envoy_yaml)
    content = envoy_path.read_text(encoding="utf-8")

    routes_blob = "\n".join(render_tenant_vhost(tenant) for tenant in tenants)
    clusters_blob = "\n".join(render_tenant_cluster(tenant) for tenant in tenants)

    content = _replace_generated_block(content, ROUTES_BEGIN_MARKER, ROUTES_END_MARKER, routes_blob)
    content = _replace_generated_block(content, CLUSTERS_BEGIN_MARKER, CLUSTERS_END_MARKER, clusters_blob)

    envoy_path.write_text(content, encoding="utf-8")
    print(f"Rendered {len(tenants)} tenant vhost(s) and cluster(s) into {args.envoy_yaml}")
    return 0


def cmd_upsert(args: argparse.Namespace) -> int:
    tenants_dir = Path(args.tenants_dir)
    tenant_dir = tenants_dir / args.name
    config_path = tenant_dir / "config.json"

    existing: dict[str, Any] = {}
    if config_path.exists():
        with config_path.open("r", encoding="utf-8") as handle:
            existing = json.load(handle)

    raw_config: dict[str, Any] = dict(existing)
    db_credentials = dict(existing.get("db_credentials") or {})
    for field in (
        "db_type",
        "db_host",
        "db_port",
        "db_name",
        "db_user",
        "db_password",
        "table_name",
        "username_col",
        "password_col",
        "role_col",
        "hash_algorithm",
    ):
        value = getattr(args, field, None)
        if value:
            db_credentials[field] = value
    raw_config.update(
        {
            "name": args.name,
            "display_name": args.display_name or existing.get("display_name") or args.name,
            "backend_url": args.backend_url,
            "hostname": args.hostname,
            "keycloak_client_id": args.keycloak_client_id or existing.get("keycloak_client_id") or args.name,
            "keycloak_realm": args.keycloak_realm or existing.get("keycloak_realm") or "test-tenant",
            "keycloak_client_secret": args.keycloak_client_secret if args.keycloak_client_secret is not None else existing.get("keycloak_client_secret", ""),
            "roles": parse_roles(args.roles),
            "login_mode": args.login_mode,
            "adapter_mode": args.adapter_mode,
            "downstream_jwt_secret": args.downstream_jwt_secret if args.downstream_jwt_secret is not None else existing.get("downstream_jwt_secret", ""),
            "redirect_uris": args.redirect_uri or existing.get("redirect_uris") or [],
            "web_origins": args.web_origin or existing.get("web_origins") or [],
            "no_spi": args.no_spi,
            "db_credentials": db_credentials,
            "created_at": existing.get("created_at") or utc_now(),
            "notes": args.notes if args.notes is not None else existing.get("notes", ""),
        }
    )
    if "permissions" not in raw_config:
        raw_config["permissions"] = normalize_permissions(None, raw_config["roles"])

    save_tenant_config(tenants_dir, raw_config)
    print(f"Saved tenant config: {config_path}")
    return 0


def cmd_assess(args: argparse.Namespace) -> int:
    roles = parse_roles(args.roles)
    candidate_paths = args.path or DEFAULT_ASSESS_PATHS
    report = assess_backend(
        args.backend_url,
        candidate_paths=candidate_paths,
        insecure=args.insecure,
        timeout=args.timeout,
    )

    print(f"Backend: {report['backend_url']}")
    print(f"Verdict: {report['integration_verdict']}")
    print(f"Recommended login mode: {report['recommended_login_mode']}")
    print("Summary:")
    for line in report["summary"]:
        print(f"  - {line}")

    print("Probe results:")
    for finding in report["findings"]:
        suffix = ""
        if finding["location"]:
            suffix += f" -> {finding['location']}"
        if finding["error"]:
            suffix += f" [error: {finding['error']}]"
        print(f"  - {finding['path']}: HTTP {finding['status']}{suffix}")

    if report["login_hints"]:
        print("Login hints:")
        for hint in report["login_hints"]:
            print(f"  - {hint}")

    if report["risk_notes"]:
        print("Risk notes:")
        for note in report["risk_notes"]:
            print(f"  - {note}")

    if args.write_config:
        if not args.name or not args.hostname:
            raise ValueError("--name and --hostname are required with --write-config")
        tenants_dir = Path(args.tenants_dir)
        config_path = tenants_dir / args.name / "config.json"
        existing: dict[str, Any] = {}
        if config_path.exists() and not args.force:
            raise ValueError(f"tenant config already exists: {config_path} (use --force to overwrite)")
        if config_path.exists() and args.force:
            with config_path.open("r", encoding="utf-8") as handle:
                existing = json.load(handle)

        raw_config: dict[str, Any] = dict(existing)
        raw_config.update(
            {
                "name": args.name,
                "display_name": args.display_name or existing.get("display_name") or args.name,
                "backend_url": args.backend_url,
                "hostname": args.hostname,
                "keycloak_client_id": args.keycloak_client_id or existing.get("keycloak_client_id") or args.name,
                "keycloak_realm": args.keycloak_realm or existing.get("keycloak_realm") or "test-tenant",
                "keycloak_client_secret": args.keycloak_client_secret if args.keycloak_client_secret is not None else existing.get("keycloak_client_secret", ""),
                "roles": roles,
                "login_mode": args.login_mode if args.login_mode != "auto" else report["recommended_login_mode"],
                "adapter_mode": args.adapter_mode,
                "downstream_jwt_secret": args.downstream_jwt_secret if args.downstream_jwt_secret is not None else existing.get("downstream_jwt_secret", ""),
                "redirect_uris": args.redirect_uri or existing.get("redirect_uris") or [],
                "web_origins": args.web_origin or existing.get("web_origins") or [],
                "no_spi": args.no_spi,
                "db_credentials": {
                    **(existing.get("db_credentials") or {}),
                    **{
                        key: value for key, value in {
                            "db_type": args.db_type,
                            "db_host": args.db_host,
                            "db_port": args.db_port,
                            "db_name": args.db_name,
                            "db_user": args.db_user,
                            "db_password": args.db_password,
                            "table_name": args.table_name,
                            "username_col": args.username_col,
                            "password_col": args.password_col,
                            "role_col": args.role_col,
                            "hash_algorithm": args.hash_algorithm,
                        }.items() if value
                    },
                },
                "created_at": existing.get("created_at") or utc_now(),
                "notes": args.notes if args.notes is not None else "Generated by tenant_manager assess",
            }
        )
        if "permissions" not in raw_config:
            raw_config["permissions"] = normalize_permissions(None, roles)
        written = save_tenant_config(tenants_dir, raw_config)
        print(f"Starter tenant config written: {written}")

    return 0


def cmd_delete(args: argparse.Namespace) -> int:
    tenant_dir = Path(args.tenants_dir) / args.name
    if not tenant_dir.exists():
        print(f"Tenant config not found: {tenant_dir}")
        return 0
    shutil.rmtree(tenant_dir)
    print(f"Deleted tenant config: {tenant_dir}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    default_tenants_dir = str(Path(__file__).resolve().parents[1] / "tenants")

    parser = argparse.ArgumentParser(description="Manage ZTAM tenant configs")
    parser.add_argument(
        "--tenants-dir",
        default=default_tenants_dir,
        help="Directory containing per-tenant config folders",
    )

    tenants_parent = argparse.ArgumentParser(add_help=False)
    tenants_parent.add_argument(
        "--tenants-dir",
        default=default_tenants_dir,
        help="Directory containing per-tenant config folders",
    )

    subparsers = parser.add_subparsers(dest="command", required=True)

    list_parser = subparsers.add_parser("list", parents=[tenants_parent], help="List tenant configs")
    list_parser.set_defaults(func=cmd_list)

    validate_parser = subparsers.add_parser("validate", parents=[tenants_parent], help="Validate tenant configs")
    validate_parser.set_defaults(func=cmd_validate)

    sync_parser = subparsers.add_parser(
        "sync-policies",
        parents=[tenants_parent],
        help="Generate policies/tenants.json from tenant configs",
    )
    sync_parser.add_argument(
        "--output",
        default=str(Path(__file__).resolve().parents[1] / "policies" / "tenants.json"),
        help="Path to generated tenant policy data",
    )
    sync_parser.set_defaults(func=cmd_sync_policies)

    auth_parser = subparsers.add_parser(
        "sync-auth",
        parents=[tenants_parent],
        help="Generate platform/published/auth/tenants.json from tenant configs",
    )
    auth_parser.add_argument(
        "--output",
        default=str(Path(__file__).resolve().parents[1] / "platform" / "published" / "auth" / "tenants.json"),
        help="Path to generated auth tenant metadata",
    )
    auth_parser.set_defaults(func=cmd_sync_auth)

    envoy_parser = subparsers.add_parser(
        "sync-envoy",
        parents=[tenants_parent],
        help="Render tenant routes and clusters into envoy/envoy.yaml",
    )
    envoy_parser.add_argument(
        "--envoy-yaml",
        default=str(Path(__file__).resolve().parents[1] / "envoy" / "envoy.yaml"),
        help="Path to the Envoy config file",
    )
    envoy_parser.set_defaults(func=cmd_sync_envoy)

    upsert_parser = subparsers.add_parser("upsert", parents=[tenants_parent], help="Create or update a tenant config")
    upsert_parser.add_argument("--name", required=True)
    upsert_parser.add_argument("--backend-url", required=True)
    upsert_parser.add_argument("--hostname", required=True)
    upsert_parser.add_argument("--roles", required=True)
    upsert_parser.add_argument("--display-name")
    upsert_parser.add_argument("--keycloak-client-id")
    upsert_parser.add_argument("--keycloak-realm")
    upsert_parser.add_argument("--keycloak-client-secret")
    upsert_parser.add_argument("--login-mode", default="form", choices=["form", "keycloak"])
    upsert_parser.add_argument("--adapter-mode", default="headers", choices=["headers", "translated_token"])
    upsert_parser.add_argument("--downstream-jwt-secret")
    upsert_parser.add_argument("--redirect-uri", action="append")
    upsert_parser.add_argument("--web-origin", action="append")
    upsert_parser.add_argument("--no-spi", action="store_true")
    upsert_parser.add_argument("--db-type")
    upsert_parser.add_argument("--db-host")
    upsert_parser.add_argument("--db-port")
    upsert_parser.add_argument("--db-name")
    upsert_parser.add_argument("--db-user")
    upsert_parser.add_argument("--db-password")
    upsert_parser.add_argument("--table-name")
    upsert_parser.add_argument("--username-col")
    upsert_parser.add_argument("--password-col")
    upsert_parser.add_argument("--role-col")
    upsert_parser.add_argument("--hash-algorithm")
    upsert_parser.add_argument("--notes")
    upsert_parser.set_defaults(func=cmd_upsert)

    assess_parser = subparsers.add_parser(
        "assess",
        parents=[tenants_parent],
        help="Probe a backend URL and optionally generate a starter tenant config",
    )
    assess_parser.add_argument("--backend-url", required=True)
    assess_parser.add_argument("--path", action="append", help="Path to probe; may be passed multiple times")
    assess_parser.add_argument("--timeout", type=int, default=15)
    assess_parser.add_argument("--insecure", action="store_true")
    assess_parser.add_argument("--write-config", action="store_true")
    assess_parser.add_argument("--force", action="store_true")
    assess_parser.add_argument("--name")
    assess_parser.add_argument("--hostname")
    assess_parser.add_argument("--roles", default="admin,editor,user,viewer")
    assess_parser.add_argument("--display-name")
    assess_parser.add_argument("--keycloak-client-id")
    assess_parser.add_argument("--keycloak-realm")
    assess_parser.add_argument("--keycloak-client-secret")
    assess_parser.add_argument("--login-mode", default="auto", choices=["auto", "form", "keycloak"])
    assess_parser.add_argument("--adapter-mode", default="headers", choices=["headers", "translated_token"])
    assess_parser.add_argument("--downstream-jwt-secret")
    assess_parser.add_argument("--redirect-uri", action="append")
    assess_parser.add_argument("--web-origin", action="append")
    assess_parser.add_argument("--no-spi", action="store_true")
    assess_parser.add_argument("--db-type")
    assess_parser.add_argument("--db-host")
    assess_parser.add_argument("--db-port")
    assess_parser.add_argument("--db-name")
    assess_parser.add_argument("--db-user")
    assess_parser.add_argument("--db-password")
    assess_parser.add_argument("--table-name")
    assess_parser.add_argument("--username-col")
    assess_parser.add_argument("--password-col")
    assess_parser.add_argument("--role-col")
    assess_parser.add_argument("--hash-algorithm")
    assess_parser.add_argument("--notes")
    assess_parser.set_defaults(func=cmd_assess)

    delete_parser = subparsers.add_parser("delete", parents=[tenants_parent], help="Delete a tenant config")
    delete_parser.add_argument("--name", required=True)
    delete_parser.set_defaults(func=cmd_delete)

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    try:
        return int(args.func(args))
    except ValueError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    except FileNotFoundError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
